version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: meshmonitor_web_1
      APP_PORT: 3001

  web:
    image: ghcr.io/yeraze/meshmonitor:latest
    container_name: meshmonitor_web_1
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - TZ=America/Chicago
      # REPLACE THE IP BELOW WITH YOUR MESHTASTIC NODE IP
      - MESHTASTIC_NODE_IP=meshtastic.local
      # This ensures the map tiles work correctly behind Umbrel's proxy
      - ALLOWED_ORIGINS=*
